#!/usr/bin/env python3
"""Sync Bundle drawables from one pinned Rules commit; never converts web SVGs."""
import argparse
import io
import json
from pathlib import Path
import re
import subprocess
import tarfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
MAP = Path('library/src/main/java/com/absinthe/rulesbundle/IconResMap.kt')
DRAWABLES = Path('library/src/main/res/drawable')
ICON = re.compile(r'ic_lib_[a-z0-9_]+')


def generate(index, vectors, previous, revision):
    if index.get('-1') != {'iconId': None, 'isSimpleColorIcon': True}:
        raise ValueError('Missing stable -1 placeholder mapping')
    numbers = sorted(int(key) for key in index if key != '-1')
    if numbers != list(range(len(numbers))) or set(index) != {str(n) for n in [-1] + numbers}:
        raise ValueError('Icon indexes must be contiguous canonical integers')
    old = re.findall(r'/\* (\d+)(?:: (ic_lib_[a-z0-9_]+))? \*/ R\.drawable\.(\w+)', previous)
    for number, source_id, resource in old:
        if number not in index or index[number]['iconId'] != (source_id or resource):
            raise ValueError(f'Cannot remove or reassign existing icon index {number}')
    lines, simple, files, seen = [], [-1], {}, set()
    tags = {'vector', 'group', 'path', 'clip-path', 'gradient', 'item',
            '{http://schemas.android.com/aapt}attr'}
    for number in numbers:
        item = index[str(number)]
        name = item.get('iconId')
        if not isinstance(name, str) or not ICON.fullmatch(name) or name in seen:
            raise ValueError(f'Invalid or duplicate icon ID at {number}')
        if type(item.get('isSimpleColorIcon')) is not bool:
            raise ValueError(f'Invalid color flag at {number}')
        seen.add(name)
        raw = vectors.get(name)
        resource = 'ic_sdk_placeholder'
        if raw is not None:
            if len(raw) > 256 * 1024 or b'<!DOCTYPE' in raw.upper() or b'<!ENTITY' in raw.upper():
                raise ValueError(f'Unsafe vector XML: {name}')
            tree = ET.fromstring(raw)
            if tree.tag != 'vector' or any(node.tag not in tags for node in tree.iter()):
                raise ValueError(f'Not a supported VectorDrawable: {name}')
            files[DRAWABLES / f'{name}.xml'] = raw
            resource = name
        elif re.search(rf'R\.drawable\.{re.escape(name)}\b', previous):
            raise ValueError(f'Existing Android vector cannot silently disappear: {name}')
        lines.append(f'        /* {number}: {name} */ R.drawable.{resource},')
        if item['isSimpleColorIcon'] or raw is None:
            simple.append(number)
    text = '''package com.absinthe.rulesbundle

import com.absinthe.lc.rulesbundle.R

// Generated by tools/sync_android_icons.py from Rules commit REVISION.
// Numeric source IDs remain stable; web-only icons use the Android placeholder.
object IconResMap {
    private const val PLACEHOLDER_INDEX = -1

    private val iconResIds = intArrayOf(
ROWS
    )

    private val singleColorIconIndexes = setOf(COLORS)

    fun getResIndex(res: Int): Int {
        if (res == R.drawable.ic_sdk_placeholder) return PLACEHOLDER_INDEX
        val index = iconResIds.indexOf(res)
        return if (index >= 0) index else PLACEHOLDER_INDEX
    }

    fun getIconRes(index: Int): Int {
        return if (index in iconResIds.indices) iconResIds[index] else R.drawable.ic_sdk_placeholder
    }

    fun isSingleColorIcon(index: Int) = index !in iconResIds.indices || singleColorIconIndexes.contains(index)
}
'''.replace('REVISION', revision).replace('ROWS', '\n'.join(lines)).replace('COLORS', ', '.join(map(str, simple)))
    files[MAP] = text.encode()
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--rules-dir', type=Path, required=True)
    parser.add_argument('--revision', required=True, help='Full committed Rules SHA, never a floating branch')
    parser.add_argument('--check', action='store_true', help='Verify generated resources without writing')
    args = parser.parse_args()
    if not re.fullmatch(r'[0-9a-f]{40}', args.revision):
        parser.error('--revision must be a full Git commit SHA')
    try:
        archive = subprocess.check_output(['git', '-C', str(args.rules_dir), 'archive', args.revision, 'icons'])
        with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
            index = json.load(tar.extractfile('icons/index.json'))
            vectors = {Path(m.name).stem: tar.extractfile(m).read() for m in tar.getmembers()
                       if m.isfile() and re.fullmatch(r'icons/android/ic_lib_[a-z0-9_]+\.xml', m.name)}
        files = generate(index, vectors, (ROOT / MAP).read_text(), args.revision)
        changed = [p for p, raw in files.items() if not (ROOT / p).is_file() or (ROOT / p).read_bytes() != raw]
        if args.check and changed:
            raise ValueError('Outdated Android resources: ' + ', '.join(map(str, changed)))
        if not args.check:
            for path in changed:
                (ROOT / path).write_bytes(files[path])
        print(f'{len(files) - 1} vectors verified at {args.revision}; {len(changed)} changed files')
    except (ValueError, OSError, ET.ParseError, KeyError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'{error}\n')


if __name__ == '__main__':
    main()
